mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tournament_app.urls')),
    path('invitations/', include('invitations.urls', namespace= 'invitations')),
]

mysite/tournament_app/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from  . import views

app_name = 'tournament_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('users', views.user_list, name='user_list'),
    path('user/<int:pk>/', views.user_details, name='user_details'),
    path('tournaments', views.tournament_list, name ='tournament_list'),
    path('tournament/<int:pk>/', views.tournament_details, name='tournament_details'),
    path('teams', views.team_list, name='team_list'),
    path('team/<int:pk>/', views.team_details, name='team_details'),
    path('match/<int:tournament_pk>/<int:match_pk>/', views.match_details, name='match_details'),
    path('register', views.register_request, name='register'),
    path('login', views.login_request, name='login' ),
    path('logout', views.logout_request, name='logout'),
    path('create_team', views.create_team, name='create_team'),
    path('update_team/<int:pk>/', views.update_team, name='update_team'),
    path('delete_team/<int:pk>/', views.delete_team, name='delete_team'),
    path('update_user/<int:pk>/', views.update_user, name='update_user'),
    path('invite_user/<int:pk>/', views.invite_user, name='invite_user'),
    path('get_invitation/<int:pk>/', views.get_invitation, name='get_invitation'),
    path('search/', views.search, name='search'),
    path('remove_player/<int:team_pk>/<int:player_pk>/', views.remove_player, name='remove_player'),
    path('leave_team/<int:pk>/', views.leave_team, name='leave_team'),
    path('join_tournament/<int:tournament_pk>/<int:team_pk>/', views.join_tournament, name='join_tournament'),
    path('leave_tournament/<int:tournament_pk>/<int:team_pk>/', views.leave_tournament, name='leave_tournament'),
    path('start_tournament/<int:pk>/', views.start_tournament, name='start_tournament'),
    path('randomize_teams/<int:pk>/', views.randomize_teams, name='randomize_teams'),
    path('finish_round/<int:pk>/', views.finish_round, name='finish_round'),
    path('save_match/<int:tournament_pk>/<int:match_pk>/', views.save_match, name='save_match'),
    path('finish_tournament/<int:pk>/', views.finish_tournament, name='finish_tournament'),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mysite/tournament_app/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

from .models import Team, Invitation, Match, Tournament

User = get_user_model()

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")
    
    def save(self, commit = True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

class TeamForm(ModelForm):

    class Meta:
        model = Team
        fields = ("logo", "name", "description")

class UserForm(ModelForm):

    class Meta:
        model = User
        fields = ("logo", "info")

class InvitationForm(ModelForm):
    recipient = forms.ModelChoiceField(queryset=User.objects.filter(is_team=False), label='Użytkownik')
    
    class Meta:
        model = Invitation
        fields =  ("recipient", "title", "message")


class AcceptInvitationForm(forms.Form):
    accept = forms.ChoiceField(label='Czy zaakceptować zaproszenie?', choices=[('Tak', 'Tak'), ('Nie', 'Nie')], widget=forms.RadioSelect)

class WinnerTeam(ModelForm):
    
    class Meta:
        model = Match
        fields = ['winner']
    winner = forms.ModelChoiceField(queryset=Team.objects.all(), widget=forms.RadioSelect, empty_label=None)

class MVPForm(ModelForm):
    class Meta:
        model = Tournament
        fields = ['MVP']

    def __init__(self, remaining_team, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['MVP'].queryset = remaining_team.players.all()


    
    
    

mysite/tournament_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import NewUserForm, TeamForm, UserForm, InvitationForm, AcceptInvitationForm, WinnerTeam, MVPForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from random import shuffle

from .models import Tournament, User, Team, Invitation, Match


def index(request):
    return render(request, 'tournament_app/index.html')

def user_list(request):
    user_list = User.objects.order_by('id')
    return render(request, 'tournament_app/user_list.html', context={'user_list': user_list})

def user_details(request, pk):
    user = get_object_or_404(User, pk=pk)
    return render(request, 'tournament_app/user.html', context={'user': user})

def tournament_list(request):
    tournaments = Tournament.objects.order_by('id')
    return render(request, 'tournament_app/tournaments.html', context = {'tournaments' : tournaments})

def tournament_details(request, pk):
    tournament_details = get_object_or_404(Tournament, pk = pk)
    return render(request, 'tournament_app/tournament.html', context = {'tournament' : tournament_details})

def team_list(request):
    team_list = Team.objects.order_by('id')
    return render(request, 'tournament_app/teams.html', context= {'team_list': team_list})

def team_details(request, pk):
    team_details = get_object_or_404(Team, pk = pk)
    return render(request, 'tournament_app/team.html', context = {'team': team_details})

def match_details(request, tournament_pk, match_pk):
    tournament = get_object_or_404(Tournament, pk=tournament_pk)
    match = get_object_or_404(Match, pk=match_pk)
    return render(request, 'tournament_app/match.html', context={'tournament': tournament, 'match': match})

def register_request(request):
    if request.user.is_authenticated:
        return redirect('tournament_app:index')
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            request.session['logged_in_user'] = user.id
            request.session.get('logged_in_user', None)
            messages.success(request, 'Pomyślnie zarejestrowano!')
            return redirect('tournament_app:index')
        messages.error(request, 'Rejestracja nieudana!')
    form = NewUserForm()
    return render(request=request, template_name='tournament_app/register.html', context={'register_form': form})

def login_request(request):
    if request.user.is_authenticated:
        return redirect('tournament_app:index')
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password = password)
            if user is not None:
                login(request, user)
                request.session['logged_in_user'] = user.id
                request.session.get('logged_in_user', None)
                messages.success(request, 'Pomyślnie zalogowano!')
                return redirect('tournament_app:index')
            else: 
                messages.error(request, 'Błędna nazwa użytkownika lub hasło!')
        else:
            messages.error(request,'Błędna nazwa użytkownika lub hasło!')
    form = AuthenticationForm()
    return render(request=request, template_name='tournament_app/login.html', context={'login_form': form})
        

def logout_request(request):
    if 'logged_in_user' in request.session:
        del request.session['logged_in_user']
    logout(request)
    messages.success(request, 'Pomyślnie wylogowano.')
    return redirect('tournament_app:index')

@login_required(login_url='/login', redirect_field_name='next')
def create_team(request):
    if(request.user.is_team):
        return redirect('tournament_app:index' )
    else:
        if request.method == 'POST':
            form = TeamForm(request.POST, request.FILES)
            if form.is_valid():
                team = form.save(commit=False)
                team.leader = request.user
                User.objects.filter(pk=request.user.id).update(is_team=True)
                team.save()
                team.players.add(request.user)
                messages.success(request, 'Pomyślnie utworzono drużynę!')
                return redirect('tournament_app:team_details', pk=team.pk)
        else:
            form = TeamForm
        return render(request, 'tournament_app/create_team.html', context={'form': form})

@login_required(login_url='/login', redirect_field_name='next')
def update_team(request, pk): 
        team = get_object_or_404(Team, pk=pk)
        form = TeamForm(request.POST or None, request.FILES, instance=team)
        if request.user.id != team.leader.id:
            return render(request, 'tournament_app/index.html')
        else:
            if request.method == 'POST':
                if form.is_valid():
                    form.save()
                    messages.success(request, 'Pomyślnie zaktualizowano dane drużyny!')
                    return redirect('tournament_app:team_details', pk = team.pk)
                else:
                    messages.error(request, 'Nie udało się zaktualizować danych drużyny!')
                    return redirect('tournament_app:index.html')
            else: 
                form = TeamForm(instance=team)
            return render(request, 'tournament_app/update_team.html', context={'team': team, 'form': form})

@login_required(login_url='/login')
def delete_team(request,pk):
    team = get_object_or_404(Team, pk=pk)
    if request.user.id != team.leader.id:
        return render(request, 'tournament_app/index.html')
    else:
        if request.method == 'POST':
            for player in team.players.all():
                player.is_team = False
                player.save()
            team.delete()
            messages.success(request, 'Pomyślnie usunięto drużynę!')
            return redirect('tournament_app:index')
        return render(request, 'tournament_app/delete_team.html', context={'team': team})

@login_required(login_url='/login')
def remove_player(request, team_pk, player_pk):
    team = get_object_or_404(Team, pk=team_pk)
    player = get_object_or_404(User, pk=player_pk)
    if request.user.id != team.leader.id or player not in team.players.all():
        messages.error(request, 'Nie masz do tego dostępu!')
        return render(request, 'tournament_app/index.html')
    if request.method == 'POST':
        team.players.remove(player)
        User.objects.filter(pk=player_pk).update(is_team=False)
        messages.success(request, f'{player.username} został usunięty z drużyny {team.name}')
        return redirect('tournament_app:team_details', pk=team.pk)
    else:
        return render(request, 'tournament_app/remove_player.html', context={'team': team, 'player': player})

@login_required(login_url='/login')
def leave_team(request, pk):
    team = get_object_or_404(Team, pk=pk)
    user = request.user
    if request.user.id == team.leader.id:
        messages.error(request, 'Nie możesz wyjść, jesteś liderem tej drużyny!')
        return redirect('tournament_app:index')
    if request.method == 'POST':
        if user.is_team and user in team.players.all():
            team.players.remove(user)
            User.objects.filter(pk=user.id).update(is_team=False)
            messages.success(request, 'Opuściłeś drużynę')
            return redirect('tournament_app:index')
        else:
            messages.error(request, 'Nie jesteś w tej drużynie!')
            return redirect('tournament_app:index')
    else:
        return render(request, 'tournament_app/leave_team.html', context={'team': team})



@login_required(login_url='/login')
def update_user(request, pk):
    user = get_object_or_404(User,pk=pk)
    form = UserForm(request.POST or None, request.FILES, instance=user)
    if request.user != user:
        return redirect('tournament_app:index')
    else: 
        if request.method == 'POST':
            if form.is_valid():
                form.save()
                messages.success(request, 'Pomyślnie zaktualizowałeś Swoje dane!')
                return redirect('tournament_app:index')
            else:
                messages.error(request, 'Coś poszło nie tak!')
                return redirect('tournament_app:index')
        else:
            form = UserForm(instance=user)
        return render(request, 'tournament_app/update_user.html', context={'user': user, 'form': form})

@login_required(login_url='/login')
def invite_user(request,pk):
    team = get_object_or_404(Team,pk=pk)
    form = InvitationForm(request.POST or None)

    if request.user.id != team.leader.id:
        return redirect('tournament_app:index')
    else:
        if request.method == 'POST':
            if form.is_valid():
                invitation = form.save(commit=False)
                invitation.team = team
                invitation.sender = request.user
                try:
                    recipient = User.objects.get(username=form.cleaned_data['recipient'])
                except User.DoesNotExist:                    
                    messages.error(request, 'Podany użytkownik nie istnieje!')
                    return redirect('tournament_app:invite_user', pk=pk)
                if recipient in team.players.all():
                    messages.error(request, 'Użytkownik jest już w drużynie!')
                    return redirect('tournament_app:invite_user', pk=pk)
                if team.players.count() >= 5:
                    messages.error(request, 'Drużyna już osiągnęła maksymalny limit zawodników!')
                    return redirect('tournament_app:invite_user', pk=pk)

mysite/tournament_app/templates/tournament_app/base.html
{% include 'tournament_app/navbar.html' %}

{% load static %}

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'tournament_app/style.css' %}">
</head> 
<body>
{% block content %}
{% endblock %}
</body>

<style>
    body {
        background: linear-gradient(#fff, #e0ebeb, #fff);
    }
</style>

mysite/tournament_app/templates/tournament_app/finish_tournament.html
{% extends 'tournament_app/base.html' %}

{% block content %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }}">
{{ message }}</br></br>
</div>
{% endfor %}
{% endif %} 

<center style='padding: 20px;'>
<h2><strong>Turniej wygrała drużyna {{tournament.team.first}}!</strong></h2>

<div class="container">
    <form method="post" action='{% url 'tournament_app:finish_tournament' pk=tournament.pk%}' >
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Zakończ turniej" class='btn btn-dark'>
    </form>
</div>
</center>
{% endblock %}

mysite/tournament_app/templates/tournament_app/index.html
{% include 'tournament_app/navbar.html' %}

    
        {% load static %}
    <link rel='stylesheet' type="text/css" href='{% static 'tournament_app/style.css' %}'>
    {% block content %}
    {% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }}">
{{ message }}</br></br>
</div>
{% endfor %}
{% endif %} 
<body>
    {% if user.is_authenticated %}
        {% if user.logo %}
            <img src='{{user.logo.url}}' style='width:300px; length=300px; display: block; margin: 0 auto;'>
        {% else %}
            <img src= '{% static 'tournament_app/user.png' %}' style='width:300px; length=300px; display: block; margin: 0 auto;'>
        {% endif %}
            <h2 style='text-align:center;'><strong>{{ user.username }}</strong></h2>
        <div class='user-info-box' style='float: left; margin: 20px; border: 2px solid #ccc; padding: 20px;'>
            <p>Email: {{ user.email }}</p>
        {%if user.is_team == False %}
            <p>Drużyna: W tym momencie nie posiadasz żadnej drużyny: <a href='{% url 'tournament_app:create_team' %}'>Stwórz</a> ją właśnie teraz!</p>
        {%else %}
                {% for team in user.teams.all %}
                    <p>Drużyna: <a href="{% url 'tournament_app:team_details' pk=team.pk%}">{{ team.name }}</a></p>
                {% endfor %}
        {% endif %}
        <p>Ilość zdobytych MVP: {{ user.MVP }}</p>
        </div>
        <div class='user-info-center'>
            <div class='user-info-center-inner'>
            {% if user.info %}
                <strong>Informacje o użytkowniku</strong>{{ user.info }}
            {% else %}
                <p>Informacje o użytkowniku: Brak</p>
            {% endif %}
            {% if 'logged_in_user' in request.session %}
            <strong><a href='{% url 'tournament_app:update_user' pk=user.pk %}' >Zaktualizuj </a>Swoje dane</strong>
        </div>
            <div class='user-info-right' style='float: right; margin: 20px; border: 2px solid #ccc; padding: 20px;'>
            <strong> Zaproszenia: </strong>
            {% if invitation in user.recipient.all %}
            {% for invitation in user.recipient.all %}
            <ul>
                <li><a href='{% url 'tournament_app:get_invitation' pk=invitation.pk %}'>{{ invitation.title }}</a></li>
            </ul>
            {% endfor %}
            {% else %}
                <p> W tym momencie nie masz żadnych zaproszeń do drużyny.</p>
            {% endif %}
        {% endif %}
            </div>
        </div>
    {% else %}
    <center style='margin: 100px;'>
        <h1>Aplikacja do zarządzania turniejami esportowymi</h1>
        <p><a href="{% url 'tournament_app:login' %}">Zaloguj</a> lub <a href="{% url 'tournament_app:register' %}">Stwórz nowe konto</a> by wyświetlić informacje o użytkowniku!</p>
    </center>
    {% endif %}
    
    {% endblock %}
    </body>
    <style>
        body {
            background: linear-gradient(#fff, #e0ebeb, #fff);
        }
    </style>
    

mysite/tournament_app/templates/tournament_app/leave_tournament.html
{% extends 'tournament_app/base.html' %}

{% block content %}

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }}">
{{ message }}</br></br>
</div>
{% endfor %}
{% endif %} 

<center style='padding: 20px;'>
<h2>Opuszczenie Turnieju </h2>
<p> Czy na pewno chcesz opuścić turniej {{ tournament.name }}?</p>
<form method='POST' action='{% url 'tournament_app:leave_tournament' tournament_pk=tournament.pk team_pk=team.pk %}'>
    {% csrf_token %}
    <button type='submit' class='btn btn-danger'>Opuść Turniej</button>
    <a href='{% url 'tournament_app:tournament_details' pk=tournament.pk %}' class="btn btn-dark">Anuluj</a>
</form>
</center>
{% endblock %}

mysite/tournament_app/templates/tournament_app/navbar.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<nav class="navbar navbar-expand-lg bg-light">
  {% load static %}
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'tournament_app:index' %}"><img src= "{% static 'tournament_app/logo1.png' %}" style="width:80px;height:80px;"></a>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'tournament_app:user_list' %}">Użytkownicy</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'tournament_app:tournament_list' %}">Turnieje</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'tournament_app:team_list' %}">Druzyny</a>
        </li>
        {%if 'logged_in_user' in request.session %}
        <li class="nav-item">
          <a class="nav-link active" href="/logout">Wyloguj</a>
        </li>
        <li class="nav-item">
          <a class="nav-link">Witaj {{request.user}}! </a>
        </li>
          
        {% else %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'tournament_app:login' %}">Logowanie</a>
        </li>

        {% endif %}
      </ul>
      <form method='GET' action='{% url 'tournament_app:search' %}' class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Wyszukaj" aria-label="search" name='search'>
        <button class="btn btn-outline-dark" type="submit">Wyszukaj</button>
      </form>
    </div>
  </div>
</nav>

mysite/tournament_app/templates/tournament_app/remove_player.html
{% extends 'tournament_app/base.html' %}

{% block content %}
<center style='padding: 20px;'>
    <h2><strong>Usunięcie gracza z drużyny</strong></h2>
    <p>Czy na pewno chcesz usunąć gracza {{ player.username }} z drużyny {{ team.name }}?</p>
    <form method='POST' action='{% url 'tournament_app:remove_player' team_pk=team.pk player_pk=player.pk %}'>
        {% csrf_token %}
        <button type='submit' class='btn btn-danger'>Usuń gracza</button>
        <a href='{% url 'tournament_app:team_details' pk=team.pk %}' class="btn btn-dark">Anuluj</a>
    </form>
</center>
{% endblock %}

mysite/tournament_app/templates/tournament_app/start_tournament.html
{% extends 'tournament_app/base.html' %}

{% block content %}

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }}">
{{ message }}</br></br>
</div>
{% endfor %}
{% endif %} 

<center style='padding: 20px;'>
<h2><strong>Rozpoczęcie turnieju</strong></h2>
<p> Czy na pewno chcesz rozpocząć turniej {{ tournament.name }}?</p>
<form method='POST' action='{% url 'tournament_app:start_tournament' pk=tournament.pk %}'>
    {% csrf_token %}
    <button type='submit' class='btn btn-success'>Rozpocznij Turniej</button>
    <a href='{% url 'tournament_app:tournament_details' pk=tournament.pk %}' class="btn btn-dark">Anuluj</a>
</form>
</center>

{% endblock %}

mysite/tournament_app/templates/tournament_app/teams.html
{% extends 'tournament_app/base.html' %}

{% load static %}
<link rel='stylesheet' type="text/css" href='{% static 'tournament_app/style.css' %}'>

{% block content %}

<center>
    <h2 style='padding: 10px;'><strong>Drużyny</strong></h2>
</center>

<div class='team-view'>
{% if team_list %}

    {% for team in team_list %}
    <div class='team-view-item' style='border: 1px solid #ccc; display: flex; align-items: center; padding: 20px;'>
    {% if team.logo %}
        <img src='{{team.logo.url}}'style='width:50px; length=50px'>
    {% else %}
        <img src= '{% static 'tournament_app/team.png' %}' style='width:50px; length=50px;'>
    {% endif %}
        <a style='margin: 20px;' href="{% url 'tournament_app:team_details' pk=team.pk %}">{{ team.name }}</a></li>
    <strong style='margin: 20px'>Lider: {{ team.leader }}</strong>
    <strong style='margin: 20px;'>Liczba graczy: {{ team.players.count }}/5</strong>
    </div>
    {% endfor %}
{% else %}
    <p>Brak dostępnych drużyn.</p>
{% endif %}
</div>
<center style='padding: 10px'>
{% if user.is_anonymous %}
    <p><a href='{% url 'tournament_app:login' %}'>Zaloguj się</a> by  stworzyć Swoją drużynę!</p>
{% else %}
{%if user.is_team %}

{% else %}

    <a href='{% url 'tournament_app:create_team' %}' class="btn btn-dark">Stwórz Swoją drużynę!</a>

{% endif %}
{% endif %}
</center>
{% endblock %}

mysite/tournament_app/templates/tournament_app/tournament.html
{% extends 'tournament_app/base.html' %}

{% load static %}
<link rel='stylesheet' type="text/css" href='{% static 'tournament_app/style.css' %}'>


{% block content %}

    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
    {{ message }}</br></br>
    </div>
    {% endfor %}
    {% endif %} 


    {%if tournament.logo %}
        <img src='{{tournament.logo.url}}' style='width:300px; length=300px; display: block; margin: 0 auto;'>
    {% else %}
        <img src= '{% static 'tournament_app/tournament1.png' %}' style='width:300px; length=300px; display: block; margin: 0 auto;'>
    {% endif %}
    <h2 style='text-align:center;'><strong>{{ tournament.name }}</strong></h2>
    <div class='team-info-center'>
        <div class='team-info-center-inner'>
            {%if tournament.date %}
            <h4>Stworzono: {{tournament.date}}</h4>
            {% endif %} 
            <p><strong>Opis: </strong> {{tournament.description}}</p>
        </div>
    </div>
    <div class='team-info-box' style='float: left; margin: 20px; border: 2px solid #ccc; padding: 20px;'>
    <ul>
        {% if tournament.is_started %}
        <h4>Pozostałe Drużyny:</h4>
        {% for team in tournament.team.all %}
           <li><a href='{{ team.get_absolute_url }}'>{{team.name}}</a></li>
        {% endfor %}
        {% else %}
        <h4>Drużyny: </h4>
        {% for team in tournament.team.all %}
           <li><a href='{{ team.get_absolute_url }}'>{{team.name}}</a></li>
        {% endfor %}
        {% endif %}
    </ul>
</div> 
    <center>
    {%for team in tournament.team.all %}
        {%if request.user.id  == team.leader.id and tournament.is_started == False %}
        <a href='/leave_tournament/{{tournament.pk}}/{{team.pk}}' class='btn btn-dark'>Opuść Turniej</a>
        {% endif %}
    {% endfor %}

    <a href='{% url 'tournament_app:tournament_list' %}' class='btn btn-dark' style=''>Powrót</a>
        {% if tournament.is_started == False %}
        {% if user.is_superuser and tournament.team.count == tournament.number_of_teams %}
            <a href='{% url 'tournament_app:start_tournament' pk=tournament.pk %}' class='btn btn-dark'>Rozpocznij Turniej</a>
        {% endif %}
    {% endif %}
    {% if user.is_superuser and tournament.is_finished and  tournament.team.count  == 1 %}
            <a href='{% url 'tournament_app:finish_tournament' pk=tournament.pk %}' class='btn btn-dark'>Zakończ Turniej</a>
    {% endif %}    
    </center>

    
    {% if tournament.is_started %}
    <div class='user-info-right' style='float: right; margin: 20px; border: 2px solid #ccc; padding: 20px;'>
        <h2>Runda: {{tournament.round_number}}</h2>
        <h3>Mecze: </h3>
        {% for match in tournament.matches.all %}
            <div class='match-line' style='display: flex; justify-content: space-between;'>
                <p> {{ match.home_team.name }} vs {{match.away_team.name}}</p> 
                <a href='{% url 'tournament_app:match_details' tournament_pk=tournament.pk match_pk=match.pk %}'>Szczegóły</a>
            </div>
        {% endfor %}
        {% if user.is_superuser and tournament.is_drawed == False and tournament.team.count > 1 %}
        <a href='{% url 'tournament_app:randomize_teams' pk=tournament.pk %}' class='btn btn-dark'>Losuj Drużyny</a> 
    {% endif %} 
    {% if user.is_superuser  and tournament.is_drawed == True and tournament.team.count >= 1 %}
        <a href= '{% url 'tournament_app:finish_round' pk=tournament.pk %}' class='btn btn-dark'>Zakończ rundę</a>
    {% endif %}  
    {% endif %}
    </div> 





{% endblock %} 

mysite/tournament_app/templates/tournament_app/update_team.html
{% extends 'tournament_app/base.html' %}

{% load static %}

{% block content %}

<center style='padding: 20px;'>
    <h2><strong>Edytuj Drużyne</strong></h2>
    <br/>
    <form method=POST action='{% url 'tournament_app:update_team' pk=team.pk %}' enctype='multipart/form-data'>
        {% csrf_token %}
        {% for field in form %}
        {% if field.label %}
            <div class="form-group" style='padding: 10px;'>
                {{ field.label_tag }}
                {{ field }}
            </div>
        {% else %}
            {{ field }}
        {% endif %}
        {% endfor %}
        <input type='submit' value='Zaktualizuj' class='btn btn-success'>
        <input type='button' value='Anuluj dodawanie pliku' class='btn btn-danger' onclick='document.getElementById("id_logo").value = ""'>
        <a href='{% url 'tournament_app:team_details' pk=team.pk %}' class="btn btn-dark">Powrót</a>
    </form>
</center>

{% endblock %}